jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  integration:
    docker:
      - image: python:3.6   
    steps:
      - checkout
      - run: exit 0

  prod:
    docker:
      - image: python:3.6     
    steps:
      - checkout
      - run: echo "This is a deploy step"
    when: always  
    
  artifact:
    docker:
      - image: python:3.6
    working_directory: /tmp  
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts    

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
           - build
      - integration:
         requires:
           - test
      - artifact     
      - prod:
         requires:
           - integration       
    filters:
      branches:
        only:
          - main
